Neos:
  Media:
    assetSources:
      vimeo:
        playerDomain: 'https://player.vimeo.com'
        assetSource: 'DIU\Assetsource\Vimeo\AssetSource\VimeoAssetSource'
        assetSourceOptions:
          asyncThumbnails: true

          clientId : Vimeo-Client-Id
          clientSecret : Vimeo-Client-Secret
          accessToken : Vimeo-Access-Token

    asset:
      modelMappingStrategy:
        patterns:
          '[vimeo/video]':
            className: DIU\Assetsource\Vimeo\Domain\Model\Vimeo

  Neos:
    userInterface:
      inspector:
        dataTypes:
          DIU\Assetsource\Vimeo\Domain\Model\Vimeo:
            typeConverter: Neos\Neos\TypeConverter\EntityToIdentityConverter
            editor: Neos.Neos/Inspector/Editors/AssetEditor
            editorOptions:
              features:
                upload: true
                mediaBrowser: true
